/*
 * This source file was generated by the Gradle 'init' task
 */
package youtube_tracker;

public class App {

    public static void main(String[] args) {
        startTracking("@Google");
        startTracking("@Microsoft");
        startTracking("@Github");
    }

    public static void startTracking(String handle) {
        var trackerService = new YouTubeTrackerService(handle);
        trackerService.start();

        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
