/*
 * This source file was generated by the Gradle 'init' task
 */
package youtube_tracker;

public class App {

    public static void main(String[] args) {
        var google = new YouTubeTrackerService("@Google");
        google.start();
        var microsoft = new YouTubeTrackerService("@Microsoft");
        microsoft.start();
        var github = new YouTubeTrackerService("@Github");
        github.start();

    }
}
